# Generated by Django 5.1.5 on 2025-02-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
