# Generated by Django 5.1.5 on 2025-02-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_object',
            new_name='course_objects',
        ),
    ]
