# Generated by Django 5.1.5 on 2025-02-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_rename_course_object_order_course_objects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
