# Generated by Django 5.1.5 on 2025-02-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_rename_course_object_cart_course_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='course_objects',
            new_name='course_object',
        ),
    ]
